name: xppe
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.13
  - pip
  - pytest
  - black

  # Core data cataloging
  - ecgtools
  - intake-esm

  # Core scientific python
  - numpy
  - pandas
  - xarray
  - netcdf4
  - h5netcdf
  - cftime
  - scipy
  - metpy
  - xskillscore
  
  # Parallel computing
  - dask
  - dask-jobqueue
  - distributed

  # Visualization
  - matplotlib
  - cartopy
  - cmocean

  # IPython for jupyter notebooks
  - jupyterlab
  - ipykernel
  - nbconvert

  - pip:
      - -e .